### ISSUE TITLE
"How to use"

### ISSUE THREAD

**Issue by ayuguchi** [elhussieny/kuka_ros_zmq#1]
Hello, I'm Yuguchi from Robotics Lab @ NAIST.
I want to know how to use this repository to control KUKA LBR iiwa on ROS and V-REP.
So, which Ubuntu version, ROS version and V-REP version is this repository for?
Please add "How to use" to README.md.
Best regards.

**Comment by elhussieny** [comment]
Hi, this repo is built under Ubuntu 14.04 with ROS Indigo installed. The
used V-REP is 3.3.1.

Basically,  to run this node, you need to run the java file on the kuka
cabinet ROSComm.java then connect the cabinet with the computer with the
running kuka_ros_zmq through the ethernet. Set a static IP for this
computer 172.31.1.1 the run the node.

If the node is not compiled at first,  you need to install ZeroMQ library.

I will add more details soon.
On Jun 17, 2016 1:48 PM, "A.Yuguchi" notifications@github.com wrote:

Hello, I'm Yuguchi from Robotics Lab @ NAIST.
I want to know how to use this repository to control KUKA LBR iiwa on ROS
and V-REP.
So, which Ubuntu version, ROS version and V-REP version is this repository
for?
Please add "How to use" to README.md.
Best regards.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/elhussieny/kuka_ros_zmq/issues/1, or mute the thread
https://github.com/notifications/unsubscribe/AISGUXaHsmu-mKnFOF4fm4MfnFsgJXo8ks5qMol1gaJpZM4I4SKT
.

**Comment by ayuguchi** [comment]
Thank you very much!
If I have comments about your repository, I will ask you.
